### ISSUE TITLE
Pre lollipop problems

### ISSUE THREAD

**Issue by sedestrian** [TR4Android/AppCompat-Extension-Library#2] opened 2015-10-12 23:33 UTC
Hi, first let me say that I love your library but i'm having problems, even with your sample app your library doesn't seem to work on pre lollipop devices.

**Comment by taltstidl** [comment] 2015-10-13 13:35
@sedestrian Could you please describe what the problem is exactly? I tested it on emulators as much as I could and didn't encounter any issues. What Android version are you using? What components are causing trouble? Thanks!

**Comment by sedestrian** [comment] 2015-10-13 13:45
Well i'm using mainly 3 testing devices and some emulators, and since my implementation wasn't working on pre lollipop devices i thought that i was doing something wrong, so i downloaded your sample.apk and installed it on various android devices and it worked only on the ones with lollipop, the other devices were API v19, and v16 the component causing trouble in my app is the floating action menu

**Comment by sedestrian** [comment] 2015-10-13 13:47
also, when setting up the background dimming there's an error that says that a resource named fab_elevation is missing from the library , but this issue might be an error in my implementation

**Comment by taltstidl** [comment] 2015-10-13 14:10
@sedestrian I wasn't aware of those issues. I'll test the sample app on those emulators as soon as I can, but I'm currently a bit short in time. There shouldn't be anything on the theoretical side that should hinder the app from working on pre-Lollipop devices. I even tested on API 7. Anyway, thanks for reporting it.

**Comment by sedestrian** [comment] 2015-10-13 14:11
You're welcome, hope to be able to use your library again soon :)

**Comment by taltstidl** [comment] 2015-11-10 12:18
@sedestrian Can you check whether the latest version works for you? I changed everything to be compatible with the new 23.1.0 support library version. (See Issue #3)

**Comment by sedestrian** [comment] 2015-11-24 07:33
Hi, it's me again, i'm having some trouble resolving your new 0.1.2 library, android studio doesn't find it (yes, i have added maven { url "https://jitpack.io" } under repositories)

**Comment by taltstidl** [comment] 2015-11-24 09:27
@sedestrian You were right. There was an issue with JitPack that I just resolved. Should work fine now. Thanks for reporting it!

**Comment by sedestrian** [comment] 2015-11-24 14:03
Ok, so I've installed your new 0.1.2 sample apk on my 4.4.4 galaxy S first gen and it still crashes as soon as I open it, not sure what could be the issue but on my app the crash when I use your library is Array out of bounds on the line where I inflate the floating action menu, maybe knowing this will help

**Comment by taltstidl** [comment] 2015-11-24 14:16
@sedestrian I'll see what I can do. Thanks for helping me and thanks for your patience.

**Comment by sedestrian** [comment] 2015-11-24 14:20
I'm happy as long as I can help :)

**Comment by sedestrian** [comment] 2015-11-24 22:22
Update, this time was my bad for the floating action menu, for some weird reason i crashed it, still need to understand why exactly, but still the sample apk crashes, maybe it's not updated with 0.1.2?

**Comment by taltstidl** [comment] 2015-11-26 16:10
@sedestrian Just a note, I've finally got the emulator working and could reproduce the issue. I'm currently working on resolving it.

**Comment by taltstidl** [comment] 2015-11-26 16:45
@sedestrian Which components were you using? I found an issue with `TypefaceCompat` that crashed the sample, but the `FloatingActionMenu` works fine on my API 19 emulator.

**Comment by sedestrian** [comment] 2015-11-26 16:52
Yes, as I wrote in my last comment this time the FAM crash was my fault

**Comment by taltstidl** [comment] 2015-11-26 17:00
@sedestrian So the `FloatingActionMenu` works for you and it was just the sample app crashing? Thanks!

**Comment by taltstidl** [comment] 2015-11-26 19:56
@sedestrian If you haven't found any other issues I'll close this one. If you could take a quick look at the sample.apk on your devices that would be very nice. Emulators are good for testing, but sometimes they just don't reflect the real device. Thanks again for your help!

**Comment by sedestrian** [comment] 2015-11-30 07:33
Yes the app now works with my v19 test device, it does have a blue background under some elements like account picture etc.. but surely works :)

**Comment by taltstidl** [comment] 2015-11-30 07:39
@sedestrian Ok, thanks for checking. I'll work on the blue background and release a fix soon.

**Closed as completed** 2015-12-03 19:00 UTC
